   services:
     - type: web
       name: openpipes-backend
       env: python
       buildCommand: pip install -r requirements.txt
       startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
       envVars:
         - key: MONGODB_URL
           value: ${MONGODB_URL}
         - key: SECRET_KEY
           value: ${SECRET_KEY}
         - key: ALGORITHM
           value: ${ALGORITHM}
         - key: ACCESS_TOKEN_EXPIRE_MINUTES
           value: ${ACCESS_TOKEN_EXPIRE_MINUTES}
